apiVersion: v2
description: Inbox Agent by AppsCode
name: capi-ops-manager
version: v2024.5.8
appVersion: v0.0.1
home: https://github.com/ops-center
icon: https://cdn.appscode.com/images/products/searchlight/searchlight-512x512.png
sources:
- https://github.com/ops-center
maintainers:
- name: appscode
  email: support@appscode.com
