project:
  name: Appcatalog by AppsCode
  shortName: Appcatalog
  url: https://github.com/kubeware/dockermachine-operator
  description: Appcatalog for Kubernetes
  app: an Appcatalog
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: dockermachine-operator
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: dockermachine-operator
  namespace: kubeops
