apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-ops-manager.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-ops-manager.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: webhook-server
    {{- include "capi-ops-manager.selectorLabels" . | nindent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
