apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:capa-vpc-peering:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - vpcpeeringconnections
  verbs: ["*"]
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - routes
  - securitygrouprules
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:capa-vpc-peering:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - vpcpeeringconnections
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - routes
  - securitygrouprules
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:capa-vpc-peering:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - vpcpeeringconnections
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ec2.aws.kubedb.com
  resources:
  - routes
  - securitygrouprules
  verbs: ["get", "list", "watch"]
