apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteropsrequests.ops.klusters.dev
spec:
  group: ops.klusters.dev
  names:
    kind: ClusterOpsRequest
    listKind: ClusterOpsRequestList
    plural: clusteropsrequests
    singular: clusteropsrequest
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterOpsRequest is the Schema for the clusteropsrequests API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterOpsRequestSpec defines the desired state of ClusterOpsRequest
            properties:
              foo:
                description: Foo is an example field of ClusterOpsRequest. Edit clusteropsrequest_types.go
                  to remove/update
                type: string
            type: object
          status:
            description: ClusterOpsRequestStatus defines the observed state of ClusterOpsRequest
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
