apiVersion: v2
description: CAPI catalog by AppsCode
name: capi-catalog
version: v2024.9.24
appVersion: v0.0.3
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/searchlight/searchlight-512x512.png
sources:
- https://github.com/kluster-api
maintainers:
- name: appscode
  email: support@appscode.com
