# Default values for capi-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""


proxies:
  dockerHub: ""
  dockerLibrary: ""
  ghcr: ghcr.io
  kubernetes: registry.k8s.io
  microsoft: mcr.microsoft.com
  appscode: r.appscode.com